// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nexguild-landing/Elevated.tsx": () => import("../components/mockups/nexguild-landing/Elevated.tsx"),
  "./components/mockups/nexguild-landing/Focused.tsx": () => import("../components/mockups/nexguild-landing/Focused.tsx")
};
